# config
logo:
keywords: "ved petkar, development, angular, ved, petkar, startups, san francisco, javascript, android, mobile, ios, swift, java"
pubkey: 13DB CAA1 2633 81A7
menu:
  Topics: /tags
  About: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics: UA-51865808-3
